[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.9"
indicatif = "0.16.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
neuroflow = "0.1.3"
text_io = "0.1.10"
chess = "3.2.0"